global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: ceiba-node
    metrics_path: /metrics
    static_configs:
      - targets:
          - ceiba-node:9933

  - job_name: nawal-ai
    metrics_path: /metrics
    static_configs:
      - targets:
          - nawal-ai:8080

  - job_name: kinich-quantum
    metrics_path: /metrics
    static_configs:
      - targets:
          - kinich-quantum:8888

  - job_name: pakit-storage
    metrics_path: /metrics
    static_configs:
      - targets:
          - pakit-storage:8001
